### ISSUE TITLE
pytorch GPT Cast ERROR

### ISSUE THREAD

**Issue by ifromeast** [NVIDIA/FasterTransformer#132]
Hi, when I run `mpirun -n 1 --allow-run-as-root python ./pytorch/gpt_sample.py`, it will occur ERROR that 
```
[INFO] batch size: 8
Traceback (most recent call last):
  File "./pytorch/gpt_sample.py", line 164, in <module>
    main()
  File "./pytorch/gpt_sample.py", line 132, in main
    gpt.cuda()
  File "/home/ubuntu/FasterTransformer/build/pytorch/utils/gpt.py", line 190, in cuda
    True, self.max_batch_size, *self.weights.w)
RuntimeError: __init__() Expected a value of type 'float' for argument '_16' but instead found type 'Tensor'.
Position: 16
Value: tensor([[ 2.3773e-02,  3.8574e-02,  6.9702e-02,  ..., -9.3445e-02,
         -1.4844e-01, -1.0345e-01],
        [ 1.6678e-02,  2.3544e-02,  4.1847e-03,  ..., -2.8656e-02,
         -9.6802e-02, -1.2123e-02],
        [ 2.3483e-02,  4.2938e-02,  1.2093e-02,  ..., -4.7363e-02,
         -1.0858e-01, -5.2277e-02],
        ...,
        [-2.0889e-02,  1.3138e-02, -8.0338e-03,  ...,  2.4597e-02,
          2.1301e-02, -1.0848e-05],
        [-2.5620e-02, -2.5253e-03, -4.5395e-03,  ...,  1.2474e-02,
          1.7548e-02, -2.4719e-02],
        [-4.2236e-02,  1.8723e-02, -2.7557e-02,  ...,  4.4403e-02,
          1.4412e-02, -2.9831e-02]], device='cuda:0')
Declaration: __init__(__torch__.torch.classes.FasterTransformer.GPT _0, int _1, int _2, int _3, int _4, int _5, int _6, int _7, float _8, float _9, int _10, int _11, int _12, int _13, bool _14, int _15, float _16, Tensor _17, Tensor _18, Tensor[] _19, Tensor[] _20, Tensor[] _21, Tensor[] _22, Tensor[] _23, Tensor[] _24, Tensor[] _25, Tensor[] _26, Tensor[] _27, Tensor[] _28, Tensor[] _29, Tensor[] _30, Tensor _31, Tensor _32) -> (NoneType _0)
Cast error details: Unable to cast Python instance to C++ type (compile in debug mode for details)
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[36875,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```
Why this happen, and how to overcome it?

**Comment by byshiue** [comment]
Thanks for your feedback. We added a repetition penalty in the gpt_op, but not update the `gpt.py`. It is fixed now by temporarily setting the repetition penalty to 1.0.
