### ISSUE TITLE
Pytorch squad ERROR

### ISSUE THREAD

**Issue by ifromeast** [NVIDIA/FasterTransformer#135]
Hi, when I use dcoker image `nvcr.io/nvidia/pytorch:20.12-py3` to run `bash pytorch/scripts/run_squad.sh ori fp16`, it will occur ERROR that
>Evaluating:   0%|                                                                                                                          | 0/170 [00:18<?, ?it/s]
Traceback (most recent call last):
  File "/workspace/FasterTransformer/build/pytorch/run_squad.py", line 497, in <module>
    main()
  File "/workspace/FasterTransformer/build/pytorch/run_squad.py", line 486, in main
    result = evaluate(args, model, tokenizer, prefix=global_step)
  File "/workspace/FasterTransformer/build/pytorch/run_squad.py", line 98, in evaluate
    outputs = model(*inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 167, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 177, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
StopIteration: Caught StopIteration in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/FasterTransformer/build/pytorch/utils/modeling_bert.py", line 147, in forward
    outputs = self.bert(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/FasterTransformer/build/pytorch/utils/modeling_bert.py", line 101, in forward
    extended_attention_mask = extended_attention_mask.to(dtype=next(self.parameters()).dtype)  # fp16 compatibility
StopIteration

How can I overcome it?

**Comment by byshiue** [comment]
You can try to fix this issue by modifying the codes
```bash
            extended_attention_mask = extended_attention_mask.to(dtype=next(self.parameters()).dtype)  # fp16 compatibility
            extended_attention_mask = (1.0 - extended_attention_mask) * -10000.0

        embedding_output = self.embeddings(
            input_ids=input_ids, position_ids=position_ids, token_type_ids=token_type_ids, inputs_embeds=inputs_embeds
        )
        if self.use_ext_encoder:
            encoder_outputs = self.encoder(embedding_output, extended_attention_mask, seq_lens)
        else:
```
to
```bash
            extended_attention_mask = extended_attention_mask.to(dtype=torch.float32)  # fp16 compatibility
            extended_attention_mask = (1.0 - extended_attention_mask) * -10000.0

        embedding_output = self.embeddings(
            input_ids=input_ids, position_ids=position_ids, token_type_ids=token_type_ids, inputs_embeds=inputs_embeds
        )
        extended_attention_mask = extended_attention_mask.to(dtype=embedding_output.dtype)
        if self.use_ext_encoder:
            encoder_outputs = self.encoder(embedding_output, extended_attention_mask, seq_lens)
        else:
```
It seems to be a known issue of pytorch.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
