### ISSUE TITLE
Error when running gpt_example.py

### ISSUE THREAD

**Issue by FarzanMemarian** [NVIDIA/FasterTransformer#198]
I've followed all the steps for running gpt on TensorFlow as outlined here: https://github.com/NVIDIA/FasterTransformer/blob/dev/v5.0_beta/docs/gpt_guide.md

However, when I run the following lines:

```
./bin/gpt_gemm 4 1 32 12 64 3072 50257 1 1 
python ../examples/tensorflow/gpt/gpt_example.py --batch_size=4 \
                                                 --length=32 \
                                                 --top_k=4 \
                                                 --top_p=0.6 \
                                                 --data_type=fp16
```

I get the following error message:

```
Traceback (most recent call last):
  File "../examples/tensorflow/gpt/gpt_example.py", line 281, in <module>
    fire.Fire(sample_model)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "../examples/tensorflow/gpt/gpt_example.py", line 159, in sample_model
    op_output, sequence_length = ft_gpt_op(ckpt_dict,
  File "../examples/tensorflow/gpt/gpt_example.py", line 237, in ft_gpt_op
    output_ids, parent_ids, sequence_length, cum_log_probs = gpt_op_module.gpt(
TypeError: gpt() missing 1 required positional argument: 'post_decoder_embedding_kernel'
```

**Comment by byshiue** [comment]
We have fixed it, please try again.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
