### ISSUE TITLE
FasterTransformer GPT huggingface_gpt_convert.py can't load gpt2 model weights

### ISSUE THREAD

**Issue by vgarimellaTuring** [NVIDIA/FasterTransformer#341]
Hi,

I am trying to run huggingface_gpt_convert.py script in FasterTransformer/examples/pytorch/gpt/utils to convert the HuggingFace model https://huggingface.co/gpt2 to binary. However, I see the following error.

```
Traceback (most recent call last):
  File "huggingface_gpt_convert.py", line 203, in <module>
    split_and_convert(args)
  File "huggingface_gpt_convert.py", line 105, in split_and_convert
    model = GPT2Model.from_pretrained(args.in_file).to(torch_device)
  File "/home/vgarimella/.local/lib/python3.6/site-packages/transformers/modeling_utils.py", line 473, in from_pretrained
    "Unable to load weights from pytorch checkpoint file. "
OSError: Unable to load weights from pytorch checkpoint file. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
```

GPUType: V100-32GB
branch: main
CUDA: 10.2

**Comment by byshiue** [comment]
Please follow the template to share your environment and reproduced steps.

**Comment by vgarimellaTuring** [comment]
okay, got it.

**Comment by vgarimellaTuring** [comment]
Posted it here https://github.com/NVIDIA/FasterTransformer/issues/342  thanks!.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this bug if you still have any problem.
