### ISSUE TITLE
FasterTransformer GPT huggingface_gpt_convert.py can't load gpt2 model weights

### ISSUE THREAD

**Issue by vgarimellaTuring** [NVIDIA/FasterTransformer#342]
### Branch/Tag/Commit

main

### GPU name

V100-32GB

### CUDA Driver

10.2.89

### Reproduced Steps

```shell
1. docker run -ti --gpus all nvcr.io/nvidia/pytorch:22.03-py3 bash
2. git clone https://github.com/NVIDIA/FasterTransformer.git
3. cd FasterTransformer mkdir build && cd build
4. cd examples/pytorch/gpt/utils
5. git clone https://huggingface.co/gpt2
6. mkdir out_dir
7. python huggingface_gpt_convert.py -i gpt2-xl/ -o out_dir/ -i_g 1
```
### Error
```shell
Traceback (most recent call last):
  File "/home/vgarimella/.local/lib/python3.6/site-packages/transformers/modeling_utils.py", line 470, in from_pretrained
    state_dict = torch.load(resolved_archive_file, map_location="cpu")
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "huggingface_gpt_convert.py", line 203, in <module>
    split_and_convert(args)
  File "huggingface_gpt_convert.py", line 105, in split_and_convert
    model = GPT2Model.from_pretrained(args.in_file).to(torch_device)
  File "/home/vgarimella/.local/lib/python3.6/site-packages/transformers/modeling_utils.py", line 473, in from_pretrained
    "Unable to load weights from pytorch checkpoint file. "
OSError: Unable to load weights from pytorch checkpoint file. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True. 
```

**Comment by byshiue** [comment]
I think that's because you don't really clone the lfs files from the repo. 
You need to use
```c
git lfs clone https://huggingface.co/gpt2
```
or run `git clone` in `gpt2` folder again.

**Comment by vgarimellaTuring** [comment]
thanks! for the suggestion. Now I am not seeing any error when running huggingface_gpt_convert.py but the below line is getting printed. However, I don't see the converted binary model in the destination folder (seeing same behavior when trying out onnx_ckpt convert as well).

Fail to save the config in config.ini.

**Comment by byshiue** [comment]
Please provide the full error message.

**Comment by vgarimellaTuring** [comment]
Hi, it only prints this single line and completed execution without any files in the destination folder. Okay, will try checking the script once again.

**Comment by byshiue** [comment]
You can disable the try/except at https://github.com/NVIDIA/FasterTransformer/blob/main/examples/pytorch/gpt/utils/huggingface_gpt_convert.py#L127 to let it print more messages.

**Comment by vgarimellaTuring** [comment]
this works now, thank you!. It seems we need to save the pytorch model via torch.save(model.state_dict(),PATH) instead of torch.save(model) when generating the pytorch model file.
