### ISSUE TITLE
" undefined symbol: _ZTIN10tensorflow8OpKernelE" when loading op library

### ISSUE THREAD

**Issue by nirvanaws1980** [NVIDIA/FasterTransformer#351]
### Branch/Tag/Commit

r5.1

### Docker Image Version

nvcr.io/nvidia/tensorflow:22.05-tf2-py3

### GPU name

T4

### CUDA Driver

11.7

### Reproduced Steps

```shell
1. docker run  -it --gpus '"device=0"' nvcr.io/nvidia/tensorflow:22.05-tf2-py3
2. git clone https://github.com/NVIDIA/FasterTransformer.git && \
    cd FasterTransformer && git reset --hard a44184afa1320ffb2571f978868531bc1d373a22 && \
    mkdir build && cd build && \
    cmake -DSM=75 -DCMAKE_BUILD_TYPE=Release -DBUILD_TF=ON -DTF_PATH=/usr/local/lib/python3.8/dist-packages/tensorflow .. && \
    make
3. python

import tensorflow as tf
import os
tf.load_op_library(os.path.join('/workspace/FasterTransformer/build/lib/libtf_bert.so'))


Exception: 
root@15a3dd99c9c7:/workspace/FasterTransformer/build# python
Python 3.8.10 (default, Mar 15 2022, 12:22:08)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import os
>>> tf.load_op_library(os.path.join('/workspace/FasterTransformer/build/lib//libtf_bert.so'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/load_library.py", line 54, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /workspace/FasterTransformer/build/lib//libtf_bert.so: undefined symbol: _ZTIN10tensorflow8OpKernelE
```

**Comment by byshiue** [comment]
We only test and develop on TF1, never test on TF2. 
To run on TF2, you may need to modify something.

**Comment by nirvanaws1980** [comment]
i just tested on tf1 as well, having the same error 
1. docker run
docker run -ti --rm nvcr.io/nvidia/tensorflow:22.04-tf1-py3 bash
2. git clone fastertransformer
git clone https://github.com/NVIDIA/FasterTransformer.git &&     cd FasterTransformer && git reset --hard a44184afa1320ffb2571f978868531bc1d373a22
3. build
 mkdir build && cd build &&     cmake -DSM=80 -DCMAKE_BUILD_TYPE=Release -DBUILD_TF=ON -DTF_PATH=/usr/local/lib/python3.8/dist-packages/tensorflow_core ..
  make
4. python:

root@eeeb7a9c224a:/workspace/FasterTransformer/build/lib# python
Python 3.8.10 (default, Mar 15 2022, 12:22:08)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2022-10-21 04:51:39.036932: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
>>> import os
>>> tf.load_op_library(os.path.join('/workspace/FasterTransformer/build/lib//libtf_bert.so'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /workspace/FasterTransformer/build/lib//libtf_bert.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

**Comment by byshiue** [comment]
I have no idea for this bug. But I find it only happens on some docker. Can you try `nvcr.io/nvidia/tensorflow:22.07-tf1-py3`

**Comment by nirvanaws1980** [comment]
tried this one as well, same error when loading the (libtf_bert.so)
docker run -ti --rm nvcr.io/nvidia/tensorflow:22.07-tf1-py3  bash

root@fcc2f09d212c:/workspace# python
Python 3.8.10 (default, Mar 15 2022, 12:22:08)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2022-10-21 17:14:34.860167: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
>>> tf.__version__
'1.15.5'
>>> exit

**Comment by byshiue** [comment]
Have you rerun the cmake script and rebuild the project in the new docker?
