### ISSUE TITLE
[error] Can't convert gpt-onnx 

### ISSUE THREAD

**Issue by lambda7xx** [NVIDIA/FasterTransformer#427]
### Branch/Tag/Commit

main

### Docker Image Version

nvcr.io/nvidia/pytorch:22.09-py3

### GPU name

V100

### CUDA Driver

Driver Version: 450.80.02    CUDA Version: 11.8

### Reproduced Steps

```shell
1  docker run -ti -v /data/v-xxshi/FasterTransformer:/workspace/lambda  -p 20022:22 --gpus all    nvcr.io/nvidia/pytorch:22.09-py3 bash

2 git clone git@github.com:NVIDIA/FasterTransformer.git

3 cd FasterTransfromer mkdir build && cd build

4 cmake -DSM=xx -DCMAKE_BUILD_TYPE=Release -DBUILD_MULTI_GPU=ON .. && make -j16

5 wget https://github.com/onnx/models/blob/main/text/machine_comprehension/gpt-2/model/gpt2-10.onnx

6 python ../examples/onnx/multi_gpu_gpt/onnx_ckpt_convert.py -i gpt2-10.onnx -o ../models/onnx-models/c-model/124m/ -i_g 4

7 error message 
=============== Argument ===============
saved_dir: ../models/onnx-models/c-model/124m/
in_file: gpt2-10.onnx
trained_gpu_num: 1
infer_gpu_num: 4
========================================
/opt/conda/lib/python3.8/site-packages/onnx/__init__.py:94: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  decoded = cast(Optional[int], proto.ParseFromString(s))
Traceback (most recent call last):
  File "../examples/onnx/multi_gpu_gpt/onnx_ckpt_convert.py", line 159, in <module>
    split_and_convert(args)
  File "../examples/onnx/multi_gpu_gpt/onnx_ckpt_convert.py", line 91, in split_and_convert
    model = onnx.load(ckpt_name)
  File "/opt/conda/lib/python3.8/site-packages/onnx/__init__.py", line 116, in load_model
    model = load_model_from_string(s, format=format)
  File "/opt/conda/lib/python3.8/site-packages/onnx/__init__.py", line 153, in load_model_from_string
    return _deserialize(s, ModelProto())
  File "/opt/conda/lib/python3.8/site-packages/onnx/__init__.py", line 96, in _deserialize
    raise google.protobuf.message.DecodeError(
google.protobuf.message.DecodeError: Protobuf decoding consumed too few bytes: 13 out of 138480
```

**Comment by byshiue** [comment]
Please try 
```
wet https://github.com/onnx/models/raw/main/text/machine_comprehension/gpt-2/model/gpt2-10.onnx
``` 
to download model.

**Comment by lambda7xx** [comment]
> Please try
> 
> ```
> wget https://github.com/onnx/models/raw/main/text/machine_comprehension/gpt-2/model/gpt2-10.onnx
> ```
> 
> to download model.

I use your link and convert the model.

Then I run 
```
`
mpirun -n 8 --allow-run-as-root python ../examples/pytorch/gpt/multi_gpu_gpt_example.py --tensor_para_size=8 --pipeline_para_size=1 --ckpt_path="/workspace/lambda/models/onnx-models/c-model/124m/1-gpu"  --layer_num=12 > onnx.log 2>&1 
`
```
the error message 
```

`
Traceback (most recent call last):
  File "../examples/pytorch/gpt/multi_gpu_gpt_example.py", line 271, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "../examples/pytorch/gpt/multi_gpu_gpt_example.py", line 175, in main
    if not gpt.load(ckpt_path=args.ckpt_path):
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 460, in load
    is_load = self.weights.load(ckpt_path, tp_rank=self.tensor_para_rank,
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 259, in load
    w.extend([load_to_torch(
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 259, in <listcomp>
    w.extend([load_to_torch(
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 252, in load_to_torch
    return torch.from_numpy(np.fromfile(file_path, dtype=self.weights_data_type)).to(str_type_map[self.inference_data_type])
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/lambda/models/onnx-models/c-model/124m/1-gpu/model.layers.0.attention.query_key_value.weight.1.bin'
Traceback (most recent call last):
  File "../examples/pytorch/gpt/multi_gpu_gpt_example.py", line 271, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "../examples/pytorch/gpt/multi_gpu_gpt_example.py", line 175, in main
    if not gpt.load(ckpt_path=args.ckpt_path):
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 460, in load
    is_load = self.weights.load(ckpt_path, tp_rank=self.tensor_para_rank,
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 259, in load
    w.extend([load_to_torch(
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 259, in <listcomp>
    w.extend([load_to_torch(
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 252, in load_to_torch
    return torch.from_numpy(np.fromfile(file_path, dtype=self.weights_data_type)).to(str_type_map[self.inference_data_type])
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/lambda/models/onnx-models/c-model/124m/1-gpu/model.layers.0.attention.query_key_value.weight.4.bin'
Traceback (most recent call last):
  File "../examples/pytorch/gpt/multi_gpu_gpt_example.py", line 271, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "../examples/pytorch/gpt/multi_gpu_gpt_example.py", line 175, in main
    if not gpt.load(ckpt_path=args.ckpt_path):
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 460, in load
    is_load = self.weights.load(ckpt_path, tp_rank=self.tensor_para_rank,
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 259, in load
    w.extend([load_to_torch(
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 259, in <listcomp>
    w.extend([load_to_torch(
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 252, in load_to_torch
    return torch.from_numpy(np.fromfile(file_path, dtype=self.weights_data_type)).to(str_type_map[self.inference_data_type])
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/lambda/models/onnx-models/c-model/124m/1-gpu/model.layers.0.attention.query_key_value.weight.3.bin'
Traceback (most recent call last):
  File "../examples/pytorch/gpt/multi_gpu_gpt_example.py", line 271, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "../examples/pytorch/gpt/multi_gpu_gpt_example.py", line 175, in main
    if not gpt.load(ckpt_path=args.ckpt_path):
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 460, in load
    is_load = self.weights.load(ckpt_path, tp_rank=self.tensor_para_rank,
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 259, in load
    w.extend([load_to_torch(
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 259, in <listcomp>
    w.extend([load_to_torch(
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 252, in load_to_torch
    return torch.from_numpy(np.fromfile(file_path, dtype=self.weights_data_type)).to(str_type_map[self.inference_data_type])
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/lambda/models/onnx-models/c-model/124m/1-gpu/model.layers.0.attention.query_key_value.weight.7.bin'
Traceback (most recent call last):
  File "../examples/pytorch/gpt/multi_gpu_gpt_example.py", line 271, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "../examples/pytorch/gpt/multi_gpu_gpt_example.py", line 175, in main
    if not gpt.load(ckpt_path=args.ckpt_path):
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 460, in load
    is_load = self.weights.load(ckpt_path, tp_rank=self.tensor_para_rank,
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 259, in load
    w.extend([load_to_torch(
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 259, in <listcomp>
    w.extend([load_to_torch(
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 252, in load_to_torch
    return torch.from_numpy(np.fromfile(file_path, dtype=self.weights_data_type)).to(str_type_map[self.inference_data_type])
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/lambda/models/onnx-models/c-model/124m/1-gpu/model.layers.0.attention.query_key_value.weight.6.bin'
Traceback (most recent call last):
  File "../examples/pytorch/gpt/multi_gpu_gpt_example.py", line 271, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "../examples/pytorch/gpt/multi_gpu_gpt_example.py", line 175, in main
    if not gpt.load(ckpt_path=args.ckpt_path):
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 460, in load
    is_load = self.weights.load(ckpt_path, tp_rank=self.tensor_para_rank,
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 259, in load
    w.extend([load_to_torch(
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 259, in <listcomp>
    w.extend([load_to_torch(
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 252, in load_to_torch
    return torch.from_numpy(np.fromfile(file_path, dtype=self.weights_data_type)).to(str_type_map[self.inference_data_type])
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/lambda/models/onnx-models/c-model/124m/1-gpu/model.layers.0.attention.query_key_value.weight.5.bin'
Traceback (most recent call last):
  File "../examples/pytorch/gpt/multi_gpu_gpt_example.py", line 271, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "../examples/pytorch/gpt/multi_gpu_gpt_example.py", line 175, in main
    if not gpt.load(ckpt_path=args.ckpt_path):
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 460, in load
    is_load = self.weights.load(ckpt_path, tp_rank=self.tensor_para_rank,
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 259, in load
    w.extend([load_to_torch(
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 259, in <listcomp>
    w.extend([load_to_torch(
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 252, in load_to_torch
    return torch.from_numpy(np.fromfile(file_path, dtype=self.weights_data_type)).to(str_type_map[self.inference_data_type])
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/lambda/models/onnx-models/c-model/124m/1-gpu/model.layers.0.attention.query_key_value.weight.2.bin'
Traceback (most recent call last):
  File "../examples/pytorch/gpt/multi_gpu_gpt_example.py", line 271, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "../examples/pytorch/gpt/multi_gpu_gpt_example.py", line 175, in main
    if not gpt.load(ckpt_path=args.ckpt_path):
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 460, in load
    is_load = self.weights.load(ckpt_path, tp_rank=self.tensor_para_rank,
  File "/workspace/lambda/examples/pytorch/gpt/utils/gpt.py", line 290, in load
    assert self.max_seq_len <= wpe.size(0), (
AssertionError: max_seq_len (1024 must not exceed the value of maximum sequence length during training (768).
`
```

**Comment by rejoicesyc** [comment]
You didn't actually download the onnx weights by using `wget`,  instead you should use `git lfs` according to https://github.com/onnx/models/blob/main/README.md?plain=1#L242-L248.
