### ISSUE TITLE
error of 'FasterTransformer.GptOp'

### ISSUE THREAD

**Issue by YanyuanAI** [NVIDIA/FasterTransformer#437]
### Branch/Tag/Commit

main

### Docker Image Version

nvcr.io/nvidia/pytorch:22.09-py3

### GPU name

A30

### CUDA Driver

470.141.03

### Reproduced Steps

```shell
'''bash
nvidia-docker run -ti --gpus '"device=1"' -it --shm-size=1g --ulimit memlock=-1  --name ft_gpt -v $PWD:/workspace/ -p 8003:8003 -p 8004:8004 -p 8005:8005 nvcr.io/nvidia/pytorch:22.09-py3  bash
git clone https://github.com/NVIDIA/FasterTransformer.git
mkdir -p FasterTransformer/build
cd FasterTransformer/build
git submodule init && git submodule update
cmake -DSM=80 -DCMAKE_BUILD_TYPE=Release -DBUILD_PYT=ON -DBUILD_MULTI_GPU=ON ..
make -j 12
git clone https://huggingface.co/gpt2
python ../examples/pytorch/gpt/utils/huggingface_gpt_convert.py -i gpt2/ -o ../models/huggingface-models/c-model/gpt2 -i_g 1
python ../examples/pytorch/gpt/gpt_example.py --max_batch_size 8 --ckpt_path "../models/huggingface-models/c-model/gpt2" --data_type fp16 --time
'''
Then I got that:"RuntimeError: Tried to instantiate class 'FasterTransformer.GptOp', but it does not exist! Ensure that it is registered via torch::class_"
```

**Comment by byshiue** [comment]
Please use `multi_gpu_gpt_example.py`.  `gpt_example.py` is deprecated.

**Comment by YanyuanAI** [comment]
Hi @byshiue , when I change it to  multi_gpu_gpt_example.py, I got this error: 
```
"  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
./lib/libth_transformer.so
[WARNING] gemm_config.in is not found; using default GEMM algo
[FT][WARNING] Skip NCCL initialization since requested tensor/pipeline parallel sizes are equals to 1.
[FT][INFO] Device NVIDIA A30
[FT][ERROR] [FT][ERROR] CUDA runtime error: CUBLAS_STATUS_INVALID_VALUE /workspace/FasterTransformer/src/fastertransformer/utils/cublasMMWrapp
er.cc:115

Traceback (most recent call last):
  File "../examples/pytorch/gpt/multi_gpu_gpt_example.py", line 364, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "../examples/pytorch/gpt/multi_gpu_gpt_example.py", line 321, in main
    gen_outputs = gpt_generate_fn()
  File "../examples/pytorch/gpt/multi_gpu_gpt_example.py", line 302, in gpt_generate_fn
    tokens_batch = gpt(start_ids,
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/FasterTransformer/examples/pytorch/gpt/../../../examples/pytorch/gpt/utils/gpt.py", line 610, in forward
    outputs = self.model.forward(start_ids,
RuntimeError: [FT][ERROR]  Assertion fail: /workspace/FasterTransformer/src/fastertransformer/th_op/multi_gpu_gpt/ParallelGptOp.h:450"
```

**Comment by byshiue** [comment]
Can you run with environment variable `FT_DEBUG_LEVEL=DEBUG` again?

**Comment by YanyuanAI** [comment]
Hi @byshiue , I set the env variable, 
![image](https://user-images.githubusercontent.com/34088086/216875868-a36f0e38-f67d-4a08-bb83-aa25371f793f.png)
But the result is still the same, and there is no redundant prompt information output

**Comment by byshiue** [comment]
Can you provide the end-to-end steps? There are many bugs in the reproduced steps you provided. 
For example, when you convert model by 
```bash
python ../examples/pytorch/gpt/utils/huggingface_gpt_convert.py -i gpt2/ -o ../models/huggingface-models/c-model/gpt2 -i_g 1
```
the model is put in `../models/huggingface-models/c-model/gpt2/1-gpu/` but not `../models/huggingface-models/c-model/gpt2` and it should crash when you run the example by 
```bash
python ../examples/pytorch/gpt/gpt_example.py --max_batch_size 8 --ckpt_path "../models/huggingface-models/c-model/gpt2" --data_type fp16 --time
```
during weight loading. Besides, the default model architectures of the example is not same to gpt-2.

**Comment by YanyuanAI** [comment]
Hi @byshiue, Sorry, I checked it, and I lost the download step, the detail bash is the below:
```
bash
nvidia-docker run -ti --gpus '"device=1"' -it --shm-size=1g --ulimit memlock=-1  --name ft_gpt -v $PWD:/workspace/ -p 8003:8003 -p 8004:8004 -p 8005:8005 nvcr.io/nvidia/pytorch:22.09-py3  bash
git clone https://github.com/NVIDIA/FasterTransformer.git
mkdir -p FasterTransformer/build
cd FasterTransformer/build
git submodule init && git submodule update
cmake -DSM=80 -DCMAKE_BUILD_TYPE=Release -DBUILD_PYT=ON -DBUILD_MULTI_GPU=ON ..
make -j 12
pip install -r ../examples/pytorch/gpt/requirement.txt
wget https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-vocab.json -P ../models
wget https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-merges.txt -P ../models
git clone https://huggingface.co/gpt2
python ../examples/pytorch/gpt/utils/huggingface_gpt_convert.py -i gpt2/ -o ../models/huggingface-models/c-model/gpt2 -i_g 1
python ../examples/pytorch/gpt/gpt_example.py --max_batch_size 8 --ckpt_path "../models/huggingface-models/c-model/gpt2/1-gpu" --data_type fp16 --time
```
and I don't understand "the default model architectures of the example is not same to gpt-2.", I download the gpt-2's model
 and I set the para of "ckpt_path"

**Comment by YanyuanAI** [comment]
and my reproduce's step is followed by the official document of Nvidia, the link is `https://github.com/NVIDIA/FasterTransformer/blob/main/docs/gpt_guide.md`

**Comment by byshiue** [comment]
> and I don't understand "the default model architectures of the example is not same to gpt-2.", I download the gpt-2's model

The model hyper-parameters (like `num_layers`, `head_num`) are passed by arguments of the example. The default values does not match the model hyper-parameters of gpt-2.
