### ISSUE TITLE
What is 'internal error' on nccl_utils?

### ISSUE THREAD

**Issue by lkm2835** [NVIDIA/FasterTransformer#495]
### Branch/Tag/Commit

main

### Docker Image Version

nvcr.io/nvidia/pytorch:22.09-py3

### GPU name

A100

### CUDA Driver

470.161.03

### Reproduced Steps

```shell
https://github.com/NVIDIA/FasterTransformer/blob/main/docs/gpt_guide.md#run-meta-opt

I used `examples/pytorch/gpt/utils/huggingface_opt_convert.py` ... `-i_g 2`



export NVIDIA_TF32_OVERRIDE=0

CUDA_VISIBLE_DEVICES=0,1 \
mpirun -n 2 --allow-run-as-root \
python ../examples/pytorch/gpt/multi_gpu_gpt_example.py \
        --ckpt_path huggingface-models/c-model/$model_name/2-gpu \
        --lib_path ../lib/libth_transformer.so \
        --vocab_file $model_name/tokenizer.json \
        --merges_file $model_name/merges.txt \
        --input_len $input_len \
        --output_len $output_len \
        --max_batch_size 1 \
        --data_type fp32 \
        --weights_data_type fp32 \
        --tensor_para_size 1 \
        --pipeline_para_size 2 \
```

The problem has never occurred when using `tensor_para_size 2`, but using `pipeline_para_size 2` sometimes causes the above problem and sometimes not. (on 100% same code)

## Error Message
```
Initializing tensor and pipeline parallel...
Initializing tensor and pipeline parallel...
[INFO] WARNING: Have initialized the process group
[INFO] WARNING: Have initialized the process group
[WARNING] gemm_config.in is not found; using default GEMM algo
[WARNING] gemm_config.in is not found; using default GEMM algo
[FT][INFO] NCCL initialized rank=0 world_size=2 tensor_para=NcclParam[rank=0, world_size=1, nccl_comm=0x55ec9e850a30] pipeline_para=NcclParam[rank=0, world_size=2, nccl_comm=0x55ec9e9e7fe0]
[FT][INFO] NCCL initialized rank=1 world_size=2 tensor_para=NcclParam[rank=0, world_size=1, nccl_comm=0x55d880f2ef50] pipeline_para=NcclParam[rank=0, world_size=2, nccl_comm=0x55d8810c68e0]
[FT][INFO] Device NVIDIA A100-SXM4-40GB
[FT][INFO] Device NVIDIA A100-SXM4-40GB
Failed, NCCL error /root/FasterTransformer/src/fastertransformer/utils/nccl_utils.cc:90 'internal error'
```
Why do 'internal error' occur frequently?

**Comment by lkm2835** [comment]
```  
[FT][ERROR] [FT][ERROR] CUDA runtime error: CUBLAS_STATUS_EXECUTION_FAILED /root/FasterTransformer/src/fastertransformer/utils/cublasMMWrapper.cc:115

Traceback (most recent call last):
  File "../examples/pytorch/gpt/multi_gpu_opt_example_copy.py", line 454, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "../examples/pytorch/gpt/multi_gpu_opt_example_copy.py", line 397, in main
    gen_outputs = gpt_generate_fn()
  File "../examples/pytorch/gpt/multi_gpu_opt_example_copy.py", line 377, in gpt_generate_fn
    tokens_batch = gpt(start_ids,
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/FasterTransformer/examples/pytorch/gpt/../../../examples/pytorch/gpt/utils/gpt.py", line 610, in forward
    outputs = self.model.forward(start_ids,
RuntimeError: [FT][ERROR]  Assertion fail: /root/FasterTransformer/src/fastertransformer/th_op/multi_gpu_gpt/ParallelGptOp.h:450
```

new error on same code using `pipeline_para_size 2`

**Comment by byshiue** [comment]
You cannot use `i_g 2` during converting when you want to run pipeline_para_size = 2. `i_g` only means the tensor parallelism.

**Comment by lkm2835** [comment]
Oh, It works on 'i_g 1'. Thanks.

If I want use 4 gpus for `tensor_para_size 2` and `pipeline_para_size 2`, do I use `i_g 2`?

**Comment by byshiue** [comment]
> Oh, It works on 'i_g 1'. Thanks.
> 
> If I want use 4 gpus for `tensor_para_size 2` and `pipeline_para_size 2`, do I use `i_g 2`?

Right.
