### ISSUE TITLE
GPU Kernel performance test with empty parameter without model load

### ISSUE THREAD

**Issue by 92hyungjun** [NVIDIA/FasterTransformer#566]
### Branch/Tag/Commit

main

### Docker Image Version

nvcr.io/nvidia/pytorch:22.09-py3

### GPU name

A40

### CUDA Driver

525.105.17

### Reproduced Steps

```shell
The command I used to set up my environment is as follows :
1. docker run -it --gpus=all --ipc=host --net=host --name=faster_transformer_performance_test  nvcr.io/nvidia/pytorch:22.09-py3 bash
2. git clone https://github.com/NVIDIA/FasterTransformer.git
3. mkdir -p FasterTransformer/build
4. cd FasterTransformer/build
5. git submodule init && git submodule update
6. cmake -DSM=86 -DCMAKE_BUILD_TYPE=Release -DBUILD_PYT=ON -DBUILD_MULTI_GPU=ON ..
7. make -j48
8. pip install -r ../examples/pytorch/gpt/requirement.txt
9. wget https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-vocab.json -P ../models
10. wget https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-merges.txt -P ../models


root@S4:/workspace/FasterTransformer# git log
commit 0c128050e14b65d72b3c28c0324cc9db6f677be8 (HEAD -> main, origin/main, origin/HEAD)
Author: byshiue <bhsueh@nvidia.com>
Date:   Mon Apr 17 11:04:38 2023 +0800

    Update T5DecodingWeight.cc
    
    fix: fix loading bug of t5
```

```
root@S4:/workspace/FasterTransformer/build# nvidia-smi 
Tue Apr 18 05:02:38 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A40          Off  | 00000000:01:00.0 Off |                    0 |
|  0%   28C    P8    11W / 300W |      0MiB / 46068MiB |      0%      Default |
```

If I run the following command, I get the error. (which is as expected since I did not download the model checkpoint)
Of course I have tested the task with megatron checkpoint and it worked like a charm. :)

```
python ../examples/pytorch/gpt/multi_gpu_gpt_example.py --data_type fp16 --max_batch_size=32 --input_len=32 --output_len=32 --shared_contexts_ratio=0

Traceback (most recent call last):
  File "../examples/pytorch/gpt/multi_gpu_gpt_example.py", line 364, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "../examples/pytorch/gpt/multi_gpu_gpt_example.py", line 253, in main
    if not gpt.load(ckpt_path=args.ckpt_path):
  File "/workspace/FasterTransformer/examples/pytorch/gpt/../../../examples/pytorch/gpt/utils/gpt.py", line 540, in load
    is_load = self.weights.load(ckpt_path, tp_rank=self.tensor_para_rank,
  File "/workspace/FasterTransformer/examples/pytorch/gpt/../../../examples/pytorch/gpt/utils/gpt.py", line 262, in load
    raise FileNotFoundError(f"Failed to find {ckpt_path}")
FileNotFoundError: Failed to find ../models/megatron-models/c-model/345m/1-gpu
```

However, what I want is GPU Kernel performance test with various configuration. In fact, I don't need the pretrained model for this task; I just need the shape of them.
And since it is quite a tiring job to create a new checkpoint for every configuration (Num_head, Head_Size, Num_layers, etc), I wanted to test with an empty parameter.  
So I have looked through the code(https://github.com/NVIDIA/FasterTransformer/blob/169b8df80d568bf2337a35088c3979d207ab4495/examples/pytorch/gpt/utils/gpt.py#L105), and it seems like the feature was already implemented. 
There, I have attempt to manually remove the model load call, just to check whether it would run without it.

```
root@S4:/workspace/FasterTransformer/build# git diff
diff --git a/examples/pytorch/gpt/multi_gpu_gpt_example.py b/examples/pytorch/gpt/multi_gpu_gpt_example.py
index 89330b2..82647c9 100644
--- a/examples/pytorch/gpt/multi_gpu_gpt_example.py
+++ b/examples/pytorch/gpt/multi_gpu_gpt_example.py
@@ -250,8 +250,8 @@ def main():
                           expert_num=expert_num,
                           moe_k=moe_k,
                           moe_layer_index=moe_layer_index)
-        if not gpt.load(ckpt_path=args.ckpt_path):
-            print("[WARNING] Checkpoint file not found. Model loading is skipped.")
+        #if not gpt.load(ckpt_path=args.ckpt_path):
+        #    print("[WARNING] Checkpoint file not found. Model loading is skipped.")
     else:
         assert moe_layer_index == []
         gpt = gpt_decoder.Gpt(
```

After the modification, I get the following error if I run the code.

```
export FT_DEBUG_LEVEL=DEBUG
export FT_LOG_LEVEL=DEBUG
python ../examples/pytorch/gpt/multi_gpu_gpt_example.py --data_type fp16 --max_batch_size=32 --input_len=32 --output_len=32 --shared_contexts_ratio=0


[FT][ERROR] [FT][ERROR] CUDA runtime error: an illegal memory access was encountered /workspace/FasterTransformer/src/fastertransformer/models/multi_gpu_gpt/ParallelGpt.cc:1264 
```

I've attach the full logs(https://github.com/92hyungjun/test1231/blob/5b7345b781ea5f2fdcc65daf27fd7e75954025a5/log.txt#L4357). 
Can you instruct me a way to use empty tensor parameter without loading the model checkpoint, for the GPU kernel performance test?

Thank you. :)
```

**Comment by byshiue** [comment]
If you want to run benchmark with random weight, you can use `multi_gpu_gpt_example.cc`.

**Comment by 92hyungjun** [comment]
I will try with c++ code. However, do you have a plan to implement the feature in python "multi_gpu_gpt_example.py" ?

**Comment by byshiue** [comment]
We will consider.
