### ISSUE TITLE
undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by sfc-gh-zhwang** [NVIDIA/FasterTransformer#708]
I followed the guide [here](https://github.com/NVIDIA/FasterTransformer/blob/main/docs/bert_guide.md) and built the libth_transformer.so.

However, when I run `torch.classes.load_library('/FasterTransformer/build/lib/libth_transformer.so')` I got below error(it used to succeed in one of my containers, so I wonder if I missed some prerequirements)

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/torch/_classes.py", line 51, in load_library
    torch.ops.load_library(path)
  File "/usr/local/lib/python3.8/dist-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /models/FasterTransformer/build/lib/libth_transformer.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

**Comment by tonyw** [comment]
add add_compile_definitions(-D_GLIBCXX_USE_CXX11_ABI=0) in your CMakeLists.txt

**Comment by sfc-gh-zhwang** [comment]
@tonyw even I added that line, I still saw `-- USE_CXX11_ABI=True` output from the cmake command...

**Comment by flexwang** [comment]
If I look at the [CMakeLists.txt](https://github.com/NVIDIA/FasterTransformer/blob/main/CMakeLists.txt), the macro is based on below output, so I ended up modify this.
```
print(torch._C._GLIBCXX_USE_CXX11_ABI,end='');"
                  RESULT_VARIABLE _PYTHON_SUCCESS
                  OUTPUT_VARIABLE USE_CXX11_ABI)
```

**Comment by sfc-gh-jhilgart** [comment]
I've run into this with pytorch compiled to cuda 12 instead of cuda 11. What base image are you using?

**Comment by flexwang** [comment]
@sfc-gh-jhilgart If you look at the code, essentially the var `USE_CXX11_ABI` depends on `print(torch._C._GLIBCXX_USE_CXX11_ABI,end='')`. So either change that or just modify `CMakeLists.txt` to just set `USE_CXX11_ABI` as False
